project:
  type: website

website:
  title: "ESS330 Lab 2"
  navbar:
    left:
      - href: index.qmd
        text: Home
  repo-url: https://github.com/YOUR-USERNAME/YOUR-REPO
  repo-actions: [edit, issue]

format:
  html:
    theme: cosmo
    toc: true
