project:
  type: website

website:
  title: "ESS330 Lab 2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: analysis.qmd
        text: Analysis
      - href: results.qmd
        text: Results
output:
  html:
    toc: true
    toc-depth: 3
    number-sections: true
