project:
  type: website
  output-dir: docs

website:
  title: "ESS330 Lab 2"
  navbar:
    left:
      - href: index.qmd
        text: Home
  repo-url: https://github.com/CamGit12/ESS330_Lab2
  repo-actions: [edit, issue]

format:
  html:
    theme: cosmo
    toc: true
